# Generated by Django 4.2.9 on 2024-01-06 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Task Priority',
                'verbose_name_plural': 'Tasks priorities',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Tasks Status',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Task Type',
                'verbose_name_plural': 'Tasks Types',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Virtual Machine',
                'verbose_name_plural': 'Virtual Machines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cpu_usage', models.DecimalField(decimal_places=6, max_digits=8)),
                ('memory_usage', models.DecimalField(decimal_places=6, max_digits=8)),
                ('network_traffic', models.DecimalField(decimal_places=6, max_digits=9)),
                ('power_consumption', models.DecimalField(decimal_places=6, max_digits=9)),
                ('num_executed_instructions', models.DecimalField(decimal_places=1, max_digits=10)),
                ('execution_time', models.DecimalField(decimal_places=6, max_digits=8)),
                ('energy_efficiency', models.DecimalField(decimal_places=6, max_digits=7)),
                ('timestamp', models.DateTimeField()),
                ('tp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_priorities', to='fuzzy_cc_drf.taskpriority')),
                ('ts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='fuzzy_cc_drf.taskstatus')),
                ('tt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='fuzzy_cc_drf.tasktype')),
                ('vm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='fuzzy_cc_drf.virtualmachine')),
            ],
            options={
                'verbose_name': 'Consumption',
                'verbose_name_plural': 'Consumptions',
                'ordering': ['vm_id'],
            },
        ),
    ]
